FROM nginx:1.13.1

# RUN echo "daemon off;" >> /etc/nginx/nginx.conf
RUN rm /etc/nginx/conf.d/default.conf
COPY nginx.conf /etc/nginx/conf.d/
RUN mkdir /etc/nginx/ssl/
CMD ["nginx", "-g", "daemon off;"]
